INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 1", "Category 1", 100, "Today", "Tomorrow")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 2", "Category 2", 100, "Today", "Tomorrow")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 3", "Category 1", 100, "Today", "Tomorrow")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 4", "Category 2", 100, "Today", "Tomorrow")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 5", "Category 1", 100, "Today", "Tomorrow")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 6", "Category 2", 100, "Today", "Tomorrow")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 7", "Category 1", 100, "Today", "Tomorrow")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 8", "Category 2", 100, "Today", "Tomorrow")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 9", "Category 1", 100, "Today", "Tomorrow")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 10", "Category 2", 100, "Today", "Tomorrow")
INSERT INTO users (name, age) VALUES ("Cynthia", 18)
INSERT INTO users (name, age) VALUES ("Dianne", 18)
INSERT INTO users (name, age) VALUES ("Lana", 18)
INSERT INTO users (name, age) VALUES ("Serena", 18)
INSERT INTO users (name, age) VALUES ("Tiffany", 18)
INSERT INTO users (name, age) VALUES ("Ashlynn", 18)
INSERT INTO users (name, age) VALUES ("Alice", 18)
INSERT INTO users (name, age) VALUES ("Luna", 18)
INSERT INTO users (name, age) VALUES ("Katrina", 18)
INSERT INTO users (name, age) VALUES ("Catherine", 18)
INSERT INTO users (name, age) VALUES ("Katherine", 18)
INSERT INTO users (name, age) VALUES ("Cathyrine", 18)
INSERT INTO users (name, age) VALUES ("Kathyrine", 18)
INSERT INTO users (name, age) VALUES ("Kaitlyn", 18)
INSERT INTO users (name, age) VALUES ("Caitlyn", 18)
INSERT INTO users (name, age) VALUES ("Caitlin", 18)
INSERT INTO users (name, age) VALUES ("Kaitlin", 18)
INSERT INTO users (name, age) VALUES ("Catelyn", 18)
INSERT INTO users (name, age) VALUES ("Katelyn", 18)
INSERT INTO users (name, age) VALUES ("Katalin", 18)
